export const layoutContent = {
  header: "This is the header",
  footerMadeBy: "Made by",
  footerName: "Aaron Mendez",
  footerPoweredBy: "Powered by",
  footerTech: "Astro",
  profileAlt: "Aaron Mendez - Web Developer",
  name: "Aaron Mendez",
  cardDescription: "Obsessed with details that make the difference.",
  location: "A Coruña, Spain",
  mailTitle: "Send email to Aaron Mendez",
  mailLabel: "Send email to Aaron Mendez",
  navTools: "Tools",
  navExperience: "Experience",
  navProjects: "Projects",
  navEducation: "Education",
  navAbout: "About",
  navLanguage: "Switch to Spanish",
  jsonJobTitle: "Web Developer",
  jsonAlumniOf: "Associate Degree in Web Application Development",
  jsonKnowsAbout: [
    "JavaScript",
    "PHP",
    "CSS",
    "Tailwind CSS",
    "MySQL",
    "Git",
    "Web Development",
  ],
} as const;
